# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='users/'),
        ),
    ]
