# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170727_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='items/%Y/%m/%d'),
        ),
    ]
