# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170727_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timeposted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
