# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20170727_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.CharField(default='N/A', max_length=13),
            preserve_default=False,
        ),
    ]
