# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
