# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='timeoffered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
